/**
 * @module libp2p-bootstrap
 */
declare module "libp2p-bootstrap" {
    /**
     * Emits 'peer' events on a regular interval for each peer in the provided list.
     *
     * @constructs
     * @param {Object} options
     * @param {Array<string>} options.list - the list of peer addresses in multi-address format
     * @param {number} [options.interval] - the interval between emitting addresses (in milli-seconds)
     *
     */
    class Bootstrap {
        constructor(options: {
            list: string[];
            interval?: number;
        });
        /**
         * Start emitting events.
         */
        start(): void;
        /**
         * Stop emitting events.
         */
        stop(): void;
    }
    /** Tag
     * @type string
     */
    var tag: string;

    /**
     * NB: Always include the snippet below because its not 
     * generated by tsd-jsdoc else the test would keep failing
     * 
     * Due to some wierd behaviour in Node.JS module resolution
     * it's not possible to access 'Bootstrap' via dot notation 
     * even though its exported as
     * ```
     * exports = module.exports = Bootstrap
     * ```
     */
    export default Bootstrap;
}

